name: 'Run Terraform'
description: 'Validate and plan deploy'

runs:
  using: "composite"
  steps:
    - name: 'get PGP Key'
      run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      shell: bash
    - name: 'Install Terraform'
      run: |
        sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update
        sudo rm /usr/local/bin/terraform
        sudo apt-get install -y terraform=0.14.6
      shell: bash
    - name: 'Check Version'
      run: terraform version
      shell: bash
    - name: 'Terraform init'
      run: terraform init
      shell: bash
    - name: 'Terraform plan'
      run: terraform plan -out workspace.plan
      shell: bash
